---
title: "Final Project Presentation (ECON 370)"
output: html_document
date: "2024-12-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
transport_data = read.csv("/Users/vikram/Documents/ECON 370/Final Project/Data/Transportation_Data.csv")
event_data = read.csv("/Users/vikram/Documents/ECON 370/Final Project/Data/Time_Series_Event_Data.csv")
```

```{r}
library(tidyverse)
theme_set(hrbrthemes::theme_ipsum())
transport_data$OBS_DATE <- as.Date(transport_data$OBS_DATE, format = "%m/%d/%Y")
transport_data$Year <- format(transport_data$OBS_DATE, "%Y")
transport_data$Month = format(transport_data$OBS_DATE, "%m")
filtered_dat = transport_data |>
  select(OBS_DATE, VMT, Year, Month, PETROLEUM_D11, NATURAL_GAS_D11)

transit_data_monthly = filtered_dat |>
  filter(Year > 2013 & Year < 2024) |>
  mutate(Year = as.integer(Year), Month = as.integer(Month)) |>
  mutate(Month_Year = paste0(Month,"/", Year))

transit_mean_by_year = filtered_dat |>
  filter(Year > 2013 & Year < 2024) |>
  group_by(Year) |>
  summarize(avg_transit = mean(TRANSIT_D11),
            avg_vmt = mean(VMT))
transit_ride_by_year = ggplot(data=transit_mean_by_year, aes(x = Year, y = as.numeric(avg_transit), group=1)) + 
  geom_line(color = "blue", linewidth=1) +
  geom_point(aes(size = avg_vmt, color="darkred", alpha=0.9))+ guides(color = FALSE, alpha = FALSE) +
  labs(title = "Seasonally Adjusted Transit Ridership Since 2010", x = "Date", y = "Ridership (Thousands)", legend = "Average Vehicle Miles Traveled") + labs(size = "Avg Vehicle Miles Traveled")

```


```{r}
# Adding a column to convert months into numbers to make it easier to sort/group
new_event_data = event_data |>
  mutate(Month = as.integer(factor(Month, levels = month.name))) |>
  arrange(Year, Month) |>
  select(Year, Month, Total.Collisions, Total.Events, Total.Fatalities, Total.Injuries) |>
  filter(Year < 2024) |>
  group_by(Year, Month) |>
  summarise(Collisions = sum(Total.Collisions), Events = sum(Total.Events), Fatalities = sum(Total.Fatalities), Injuries = sum(Total.Injuries)) |>
  mutate(Month_Year = paste0(Month,"/", Year))

fatalities_by_year = new_event_data |>
  select(-Month) |>
  group_by(Year) |>
  summarise(Collisions = sum(Collisions), Events = sum(Events), Fatalities = sum(Fatalities), Injuries = sum(Injuries))

ggplot(fatalities_by_year, aes(x=Year, y=Fatalities)) +
  geom_line() +
  labs(title = "Transit Related Fatalities From 2014-2023", x="Year", y="Fatalities")
```
SUM UP THE OBSERVATIONS by YEAR AND MONTH. FIGURE OUT HOW TO DO REGION STUFF AFTER


JOINING DATA
```{r}
transit_and_events = full_join(new_event_data, transit_data_monthly, by=join_by("Month_Year"))
transit_and_events =  transit_and_events |>
  select(Month_Year, everything(), -Year.y, -Month.y) |>
  rename(Year = Year.x, Month = Month.x)
```
Graph Some Trends
```{r}
# Fatalities and Natural Gas Consumption by Year
nat_gas_events = transit_and_events |>
  group_by(Year) |>
  summarise(Natural_gas = sum(NATURAL_GAS_D11), Fatalities = sum(Fatalities), 
            Injuries = sum(Injuries))
petroleum_events = transit_and_events |>
  group_by(Year) |>
  summarise(Petroleum = sum(PETROLEUM_D11), Fatalities = sum(Fatalities), 
            Injuries = sum(Injuries))
vmt_events = transit_and_events |>
  group_by(Year) |>
  summarise(VMT = sum(VMT), Fatalities = sum(Fatalities), 
            Injuries = sum(Injuries))


a = ggplot(nat_gas_events, aes(x=Natural_gas, y=Injuries)) +
  geom_line() +
  geom_point(color = as.factor(nat_gas_events$Year))+
  geom_text(aes(label = Year), vjust = -0.5, size = 3)
  
b = ggplot(nat_gas_events, aes(x=Natural_gas, y=Fatalities)) +
  geom_line() +
  geom_point(color = as.factor(nat_gas_events$Year))+
  geom_text(aes(label = Year), vjust = -0.5, size = 3)

c = ggplot(petroleum_events, aes(x=Petroleum, y=Injuries)) +
  geom_line() +
  geom_point(color = as.factor(petroleum_events$Year))+
  geom_text(aes(label = Year), vjust = -0.5, size = 3)
d = ggplot(petroleum_events, aes(x=Petroleum, y=Fatalities)) +
  geom_line() +
  geom_point(color = as.factor(petroleum_events$Year))+
  geom_text(aes(label = Year), vjust = -0.5, size = 3)

e = ggplot(vmt_events, aes(x=VMT, y=Injuries)) +
  geom_line() +
  geom_point(color = as.factor(vmt_events$Year))+
  geom_text(aes(label = Year), vjust = -0.5, size = 3)
f = ggplot(vmt_events, aes(x=VMT, y=Fatalities)) +
  geom_line() +
  geom_point(color = as.factor(vmt_events$Year))+
  geom_text(aes(label = Year), vjust = -0.5, size = 3)

library(cowplot)

l = list(a, b, c, d, e, f)

plot_grid(plotlist = l, nrow = 3)
```
Linear Modeling

```{r}
fatality_model = lm(Fatalities ~ VMT + PETROLEUM_D11 + NATURAL_GAS_D11, data=transit_and_events)
injury_model = lm(Injuries ~ VMT + PETROLEUM_D11 + NATURAL_GAS_D11, data=transit_and_events)
fatality_summary = summary(fatality_model)
fatality_table = fatality_summary$coefficients
#KABLE THIS TABLE
summary(injury_model)
```




```{r}
event_data |>
  select(Primary.UZA.Name) |>
  filter(Primary.UZA.Name != "") |>
  group_by(Primary.UZA.Name) |>
  summarize(count = n())
```
